// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"github.com/Ivybloosom/go-zero-template/app/service/cmd/api/internal/handler/user"
	"github.com/Ivybloosom/go-zero-template/app/service/cmd/api/internal/svc"
	"net/http"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/user/getuser/:id",
				Handler: handler.UserRetrieveOneHandleHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/getalluser",
				Handler: handler.UserRetrieveAllHandleHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/add",
				Handler: handler.UserAddOneHandleHandler(serverCtx),
			},
		},
	)
}
