// Code generated by goctl. DO NOT EDIT.
package types

type UserRetrieveOneReq struct {
	Id string `path:"id"`
}

type UserRetrieveOneResp struct {
	Code int               `json:"code"`
	Msg  string            `json:"msg"`
	User map[string]string `json:"data"`
}

type UserRetrieveAllReq struct {
}

type UserRetrieveAllResp struct {
	Code  int                 `json:"code"`
	Msg   string              `json:"msg"`
	Users []map[string]string `json:"data"`
}

type UserAddOneReq struct {
	User map[string]string `json:"add"`
}

type UserAddOneResp struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}
